### EXERCISES

1. Using one of the methods from np.random create an array of size 4,4 with random numbers from 0-100. You can have these numbers be ints or floats. 
    * Find the standard deviation. Find the variance. Find the mean.  
    * Define an array that has the sum for each column.
    * Define an array that is the product of the elements of the previous array.

2. Practice using indexing for numpy arrays. 
    * Print the first row of the original (4,4) array.
    * Print the last element of the third row.
    * Print the second column. 
    * (Optional) Define an array for each column of the array. Use the np.hstack command to put all the columns back together and get the original matrix.
    
#### FINANCE APPLICATIONS

$$Cash Flow = Income - Expenses $$

  

1. Create a function that computes the cash flow when given values for income and expenses.  Make sure to return the cash flow at the end of the function.
    * Test the function with some values. 

2. Create a 1d array of 50 random values between 1-20 for Income and an array for Expenses.  
    * Define an object called Cash Flow that is equal to the result of passing these arrays through your function. 
    * Use np.argmax/min and np.max/min to determine the maximum and minimum Cash Flows from the set from these random values. 
    * Next, use np.sum to sum both the incomes and the expenses. Then, again use the function to calculate the total cash flow. 


### prob 1
Create random array and use the numpy functions - standard dev, variance, mean, sum and product

In [1]:
import numpy as np

In [7]:
rand_arr = np.random.randint(0,10,size = (4,4)) # random array of integers from 0-9 
rand_arr  # 4 cols 4 rows

array([[7, 1, 0, 9],
       [4, 5, 2, 9],
       [6, 5, 8, 2],
       [1, 6, 3, 6]])

### oops...

I made a mistake, the functions i asked you to use only work in 1 dimension. In other words one direction, for example, down the columns, or down the rows. So using them on a (4,4) array is a little weird. This is why i will use the .flatten() command to make my array 1d for the following commands.

(np.std, np.var, np.mean, np.sum, np.prod) 

In [11]:
rand_arr_1d = rand_arr.flatten() #  makes the 4,4 array 1 d 
rand_arr_1d

array([7, 1, 0, 9, 4, 5, 2, 9, 6, 5, 8, 2, 1, 6, 3, 6])

In [13]:
# stand dev
rand_std = np.std(rand_arr_1d)

# variance
rand_var = np.var(rand_arr_1d)

# mean
rand_mean = np.mean(rand_arr_1d)

# just printing each together
print('Stand Dev = ', rand_std)
print('Variance = ', rand_var)
print('Mean = ', rand_mean)

Stand Dev =  2.8034576865007255
Variance =  7.859375
Mean =  4.625


In [14]:
# sum
rand_sum = np.sum(rand_arr_1d)

# prod
rand_prod = np.prod(rand_arr_1d)

# print
print('Sum = ', rand_sum)
print('Prod = ', rand_prod)

Sum =  74
Prod =  0


### Indexing NumPy Arrays
Similar to lists but for rows and columns

In [15]:
# here is the original array
rand_arr

array([[7, 1, 0, 9],
       [4, 5, 2, 9],
       [6, 5, 8, 2],
       [1, 6, 3, 6]])

In [17]:
# first row
rand_row1 = rand_arr[0]
rand_row1  # check

array([7, 1, 0, 9])

In [20]:
# last element 3rd row
rand_last_row3 = rand_arr[2,3]
rand_last_row3

2

In [21]:
# second column
rand_col2 = rand_arr[:,1]
rand_col2

array([1, 5, 5, 6])

In [36]:
# array for each column
rand_col1 = rand_arr[:,0]
rand_col3 = rand_arr[:,2]
rand_col4 = rand_arr[:,3]

oops_arr = np.hstack((rand_col1,rand_col2,rand_col3,rand_col4))
print('Wrong', oops_arr)


new_arr = np.zeros((4,4))  # empty array to put the numbers

for i in range(4):
    new_arr[i] = np.hstack((rand_col1[i],rand_col2[i],rand_col3[i],rand_col4[i]))
new_arr

# i did not intend for this to be this hard

Wrong [7 4 6 1 1 5 5 6 0 2 8 3 9 9 2 6]


array([[7., 1., 0., 9.],
       [4., 5., 2., 9.],
       [6., 5., 8., 2.],
       [1., 6., 3., 6.]])

### Finance Application
CashFlow $ 

In [37]:
def calc_cash_flow(I,E):
    cf = I-E
    return cf

In [38]:
calc_cash_flow(100,50)

50

In [40]:
# make income array
income = 20*np.random.rand(50)
income

array([ 5.95469519, 17.22628917, 19.64795596,  5.71879644, 19.22799542,
       13.15780373,  9.58209481,  3.65473049,  7.9753794 ,  6.00244882,
        7.5891759 , 17.04881207,  5.2289402 ,  2.16414894, 10.86002589,
        0.38142265, 16.50685828, 15.03794426,  4.77574269,  1.46739204,
        0.85449516, 14.18282386,  9.25706089, 12.79356617,  7.55875263,
        8.14405275,  3.16268964, 14.53689448, 11.43960852, 12.77087443,
        5.58122402, 12.96544816,  9.92350864, 15.53956926,  7.11074982,
        0.57911524, 10.50970037, 15.33124752,  7.50975266, 17.85882699,
       13.56032793, 18.29732687,  8.28026283,  4.58134308, 13.53044586,
       12.69329369, 14.53936116, 14.67481864,  1.35316974,  9.10949455])

In [41]:
# make expenses array
expenses = 20*np.random.rand(50)
expenses

array([ 0.39923814, 13.75847286,  6.27481361,  5.16054814, 10.33328173,
       11.62679765,  8.2036623 , 15.90484291, 16.47258606,  0.05171733,
        8.222547  ,  2.77614828, 17.43800365, 17.93018149,  6.71712888,
        5.3081628 ,  2.78319147, 13.35156861,  3.61049934, 12.44970172,
        8.98176309, 13.38618897,  9.72470552, 12.27974297, 16.09966799,
        3.37962446,  4.90515483, 15.93333039, 14.53449411,  1.31135664,
       18.94313473,  1.93704158,  3.69106398, 14.18440096,  1.11539718,
        0.77211416,  1.7260266 , 13.96819548, 10.77128538, 13.46114473,
        2.51023876, 19.99653704,  9.29738831, 15.82116489,  5.9907224 ,
       19.9160663 ,  5.61257841,  6.99907863,  7.41590101,  0.49608421])

In [42]:
ind_cf = calc_cash_flow(income,expenses)
ind_cf

array([  5.55545705,   3.46781631,  13.37314236,   0.5582483 ,
         8.89471369,   1.53100607,   1.37843251, -12.25011242,
        -8.49720666,   5.9507315 ,  -0.6333711 ,  14.27266379,
       -12.20906345, -15.76603255,   4.142897  ,  -4.92674014,
        13.72366681,   1.68637565,   1.16524336, -10.98230968,
        -8.12726793,   0.79663489,  -0.46764464,   0.5138232 ,
        -8.54091536,   4.76442829,  -1.74246519,  -1.39643592,
        -3.09488559,  11.45951779, -13.3619107 ,  11.02840657,
         6.23244466,   1.3551683 ,   5.99535264,  -0.19299892,
         8.78367377,   1.36305204,  -3.26153272,   4.39768225,
        11.05008917,  -1.69921017,  -1.01712548, -11.23982181,
         7.53972346,  -7.2227726 ,   8.92678275,   7.67574001,
        -6.06273128,   8.61341034])

In [43]:
tot_inc = np.sum(income)
tot_exp = np.sum(expenses)

tot_cf = calc_cash_flow(tot_inc,tot_exp)
tot_cf

43.50377020756298