### EXERCISES

1. Use np.linspace to create an array of angles from 0 to 2$\pi$. 
    * Use the np.sin command on the array. Do the same for np.cos and np.tan. 
    * Convert the array of angles from radians to degrees. 
    
2. Create a 2 by 2 array of random integers. 
    * Transpose the matrix.
    * Find the determinant of the matrix. 
    * Find the inverse of the matrix.
    * Find the eigenvalues and eigenvectors of the matrix.
    
3. Use an array you already have or create a new one and save it as a csv file. Use ls to check the file was saved to the current directory. Read in the file again. 

#### PHYSICS PROBLEMS

PROJECTILE MOTION

A ball is launched from ground level at 10 m/s and an angle of 45 degrees. The acceleration due to gravity is -9.8 m/s$^2$ and air resistance can be neglected. 

1. Find the components of the launch velocity:
    * What is the velocity in the upward direction? Define this as  v_y.
    * What is the velocity in the horizontal direction? Define this as v_x. 
    * Determine the time of flight for the ball.
    * Determine the maximum height of the ball.
    * Determine the range of the ball.
    
2. Define a function our a few functions that solves the problem above. 

3. Now, define an array of launch velocities and pass through the function for a given angle. 

4. Do the same but for an array of angles for a given launch velocity.

5. Can you change the function with a for loop to loop through 5 different angles with 10 different launch velocities?

### prob 1
Make an array of angles from 0 to 2$\pi$

In [1]:
# import numpy
import numpy as np

In [2]:
# use np.linspace
angles = np.linspace(0,2*np.pi,5)
angles

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [3]:
# np.sin
y = np.sin(angles)
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [5]:
# np.cos
x = np.cos(angles)
x

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [7]:
# np.tan
z = np.tan(angles)
z

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16,  5.44374645e+15,
       -2.44929360e-16])

In [8]:
# convert from rads to degs
degs = np.degrees(angles)
degs

array([  0.,  90., 180., 270., 360.])

# prob 2 
Linear algebra functions in python

In [11]:
a_matrix = np.random.randint(0,9,(2,2))
a_matrix

array([[7, 5],
       [2, 4]])

In [12]:
# transpose
a_trans = a_matrix.T
a_trans

array([[7, 2],
       [5, 4]])

In [13]:
# determinant
a_det = np.linalg.det(a_matrix)
a_det

17.999999999999996

In [14]:
# inverse
a_inv = np.linalg.inv(a_matrix)
a_inv

array([[ 0.22222222, -0.27777778],
       [-0.11111111,  0.38888889]])

In [18]:
# eigenvalues and eigenvectors
eig_inf = np.linalg.eig(a_matrix)
eig_vals = eig_inf[0]
eig_vecs = eig_inf[1]
print('Eigenvalues',eig_vals)
print('Eigenvectors')
eig_vecs

Eigenvalues [9. 2.]
Eigenvectors


array([[ 0.92847669, -0.70710678],
       [ 0.37139068,  0.70710678]])

# prob 3
save an array as a file and then read in the file

In [20]:
np.savetxt('a.txt',a_matrix)

In [21]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is F885-EF5C

 Directory of C:\Users\bobby\Desktop\UB_PYTHON_COURSE\CLASS_EXERCISES

07/11/2019  09:36 AM    <DIR>          .
07/11/2019  09:36 AM    <DIR>          ..
06/25/2019  08:11 AM    <DIR>          .ipynb_checkpoints
07/11/2019  09:36 AM               102 a.txt
06/24/2019  03:00 PM           253,730 Bad_Exercises_1.html
06/17/2019  03:29 PM           258,102 Bobby_1D_ProjMotion.html
06/17/2019  11:44 AM             6,759 Bobby_1D_ProjMotion.ipynb
06/17/2019  03:30 PM           250,922 Exercises_1.html
06/05/2019  11:47 AM             2,405 Exercises_1.ipynb
06/17/2019  03:28 PM           251,452 Exercises_2.html
06/14/2019  11:20 AM             3,047 Exercises_2.ipynb
06/24/2019  02:59 PM           260,953 Exercises_3.html
06/21/2019  10:41 AM             6,539 Exercises_3.ipynb
07/01/2019  01:41 PM           280,358 Exercises_4.html
06/27/2019  11:36 AM            18,349 Exercises_4.ipynb
06/28/2019  11:38 AM           113,8

In [22]:
new_a = np.loadtxt('a.txt')
new_a

array([[7., 5.],
       [2., 4.]])

## PHYSICS PROBLEM

### PROJECTILE MOTION

##### Kinematic equations 

General

$$v_f = v_i + a t $$
$$v_f^2 = v_i^2 + 2 a d $$

Position Equations - x: left/right (horizontal) ; y: up/down (vertical)

$$d = \Delta x \text{   or   } \Delta y $$
$$x_f = x_i + v_{xi} t + \frac{1}{2} a_x t^2$$
$$y_f = y_i + v_{yi} t + \frac{1}{2} a_y t^2$$

Components of Velocity - Trig

$$v_x = v \cos(\theta)$$
$$v_y = v \sin(\theta) $$
$$a = a_y = g$$
$$ a_x = 0$$

[NOTE : Acceleration of gravity is only in Y direction]

##### Define variables
$x_i$ : Initial X position [m]

$x_f$ : X Position at time t [m]

$y_i$ : Initial Y Position [m]

$y_f$ : Y Position at time t [m]

$\theta$ : Launch Angle [degrees]

$v_i$ : Launch Velocity [m/s]

$v_{xi}$ : X-component of Launch Velocity [m/s]

$v_{yi}$ : Y-component of Launch Velocity [m/s]

$v_f$ : Veloctiy at time t [m/s]

$v_{xf}$ : X-component of Velocity at time t [m/s]

$v_{yf}$ : Y-component of Velocity at time t [m/s]

$a$ : Acceleration [m/s^2]

$a_x$ : X-component of Acceleration [m/s^2]

$a_y$ : Y-component of Acceleration [m/s^2]

$g$ : Acceleration of gravity [-10 m/s^2]

$t$ : time [s]

##### State the known values
$(x_i,y_i) = (0,0)$ [m]

$a_y = -10$ [m/s^2]

$v = 10$ [m/s]

$\theta = 45$ [degrees]


#### STEP ONE: Calculate components of Launch Velocity

Reminder:

$$v_x = v \cos(\theta)$$
$$v_y = v \sin(\theta) $$

In [23]:
# import packages
import numpy as np


In [26]:
# define launch velocity 
v_i = 10  # m/s

# define launch angle
theta = np.radians(45)

# define the components
v_xi = v_i * np.cos(theta)
v_yi = v_i * np.sin(theta)

# lets check
print('Launch Velocity', v_i)
print('Launch Angle', theta)
print('X Comp of Velo', v_xi)
print('Y Comp of Velo', v_yi)

Launch Velocity 10
Launch Angle 0.7853981633974483
X Comp of Velo 7.0710678118654755
Y Comp of Velo 7.0710678118654755


#### Determine the time to max height
Remember that acceleration is only due to gravity and is equal to -10 m/s^2. The horizontal velocity has no effect on the time the ball is in the air. 

We will use the equation:

$$v_f = v_i + a t  $$ 

where we know v_i is just the y component -> v_yi

and we know v_f is 0 at the max height.

Solve for t and we have:

$$t = \frac{-v_{yi}} {a}  $$

In [30]:
# define a 
a = -10

# lets define t_maxh using the equation above
t_maxh = -v_yi / a

# lets check
print('Time to reach max height', t_maxh, 'sec.')

Time to reach max height 0.7071067811865476 sec.


Total flight time is twice the time to max height

In [31]:
# define t_tot
t_tot = 2*t_maxh
t_tot

1.4142135623730951

#### Use t_maxh to solve for the max height

We will use the equation:

$$y_f = y_i + v_{yi} t + \frac{1}{2} a t $$

In [34]:
# define y_maxh using equation above
y_maxh = v_yi * t_maxh + 0.5 * a * t_maxh**2

# print
print('Max Height', y_maxh, 'meters')

Max Height 2.5000000000000004 meters


#### Find the range
The range is defined as the distance the projectile has traveled in the x-direction. The acceleration of gravity does not effect motion in the x-direction, and thus there is no acceleration in this direction. Therefore, the initial x-veloctiy is constant. We can use the following equation to find the range:

$$x_f = x_i + v_{xi} t $$

In [35]:
# define range using equation above
x_range = v_xi * t_tot

#print
print('Projectile Range', x_range, 'meters')

Projectile Range 10.000000000000002 meters


#### Lets right all we just did in one function

In [41]:
def calc_kinematics(v, theta):
    
    # calc components of initial velo
    v_xi = v*np.cos(theta)
    v_yi = v*np.sin(theta)
    
    # time to max height and total flight time
    t_maxh = -v_yi / a
    t_tot = 2*t_maxh
    
    # max height and range
    y_maxh = v_yi * t_maxh + 0.5 * a * t_maxh **2
    x_range = v_xi * t_tot
    
    return ('Max Height = ', y_maxh, 'meters', 'Range = ', x_range, 'meters')

In [42]:
calc_kinematics(v_i, theta)

('Max Height = ',
 2.5000000000000004,
 'meters',
 'Range = ',
 10.000000000000002,
 'meters')

#### Using function with arrays

In [44]:
# define array of velocities
v_is = np.array([1,5,10,20,100])

# call function
calc_kinematics(v_is,theta)

('Max Height = ',
 array([2.50e-02, 6.25e-01, 2.50e+00, 1.00e+01, 2.50e+02]),
 'meters',
 'Range = ',
 array([1.0e-01, 2.5e+00, 1.0e+01, 4.0e+01, 1.0e+03]),
 'meters')

In [46]:
# define array of angles
thetas = np.array([0.0000000, np.pi/4, np.pi/2, 
                   3*np.pi/4, np.pi, 5*np.pi/4,
                   3*np.pi/2, 7*np.pi/4, 2*np.pi])

#call function
calc_kinematics(v_i, thetas)

('Max Height = ',
 array([0.00000000e+00, 2.50000000e+00, 5.00000000e+00, 2.50000000e+00,
        7.49879891e-32, 2.50000000e+00, 5.00000000e+00, 2.50000000e+00,
        2.99951957e-31]),
 'meters',
 'Range = ',
 array([ 0.0000000e+00,  1.0000000e+01,  1.2246468e-15, -1.0000000e+01,
        -2.4492936e-15,  1.0000000e+01,  3.6739404e-15, -1.0000000e+01,
        -4.8985872e-15]),
 'meters')