In [1]:
import numpy as np  # yup thats it

### NumPy Mathematics
Another important aspect of using the NumPy package is its extensive amount of mathematical functions. This could be exponentials, trigonometric functions, square root, etc...

I've included a bunch of examples of using these commands but I strongly recommend visiting the NumPy documentation to see the complete list of commands.

In [2]:
# mathematical constants
print(np.pi)  
print(np.e)
np.inf

3.141592653589793
2.718281828459045


inf

In [3]:
# trig functions
print(np.sin(np.pi/2))  # takes radian values
print(np.cos(np.pi))
np.tan(np.pi)  # approximations

1.0
-1.0


-1.2246467991473532e-16

In [4]:
# radians to degress
np.degrees(np.pi)

180.0

In [5]:
# degrees to radians
np.radians(180.0)

3.141592653589793

In [7]:
print(np.e)  # is the value of e

# exponential functions
np.exp(-np.inf)


2.718281828459045


0.0

In [8]:
# linear algebra 
a = np.array([[1,2],
              [2,1]]) # define 2x2 matrix
inv_a = np.linalg.inv(a)  # inverse 
inv_a

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [10]:
# dot product of 2 matrices
np.dot(a, inv_a)

array([[1., 0.],
       [0., 1.]])

In [11]:
# transpose of a matrix
a_matrix = np.array([[1,2],[3,4]])
trans_a = a_matrix.T
print('a')
print(a_matrix)
print('transpose of a')
print(trans_a)

a
[[1 2]
 [3 4]]
transpose of a
[[1 3]
 [2 4]]


In [12]:
# determinant of a matrix
a_det = np.linalg.det(a_matrix)
a_det

-2.0000000000000004

In [13]:
# find the eigenvalues and eigenvectors of a matrix
a_eig = np.linalg.eig(a_matrix)
a_eig  # outputs in form array([eigenvalues]), array([eigenvectors])

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [14]:
# just like np.sum you can mulitply across an array
# determinant = product of eigenvalues
det = np.prod(a_eig[0])  # the first element of a_eig are the eigvalues
det 

-1.9999999999999998

In [15]:
# to show how python approximates
det == a_det

False

In [16]:
round(det) == round(a_det)

True

In [18]:
round(5.9999)

6

### Saving and Reading Data Files
This will be brief but I should mention these functions as a part of the NumPy package. We will revisit saving and reading data files later in the course.

In [19]:
# create random array to be saved as datafile
ex_datafile = np.random.randint(0,10,size = (10,10))
ex_datafile 

array([[4, 4, 2, 7, 1, 7, 3, 9, 2, 8],
       [5, 7, 6, 1, 6, 0, 2, 2, 5, 1],
       [6, 2, 8, 6, 8, 9, 9, 6, 2, 3],
       [8, 5, 1, 1, 1, 6, 5, 3, 2, 1],
       [0, 1, 0, 3, 3, 0, 2, 4, 3, 4],
       [7, 9, 7, 0, 7, 0, 2, 6, 9, 3],
       [1, 0, 9, 2, 6, 2, 4, 2, 3, 7],
       [2, 2, 5, 1, 6, 0, 0, 7, 9, 8],
       [9, 3, 4, 5, 3, 5, 0, 4, 6, 6],
       [1, 7, 1, 8, 5, 5, 6, 3, 5, 9]])

In [31]:
# save numpy array as csv
np.savetxt("datafile.csv", ex_datafile)

In [32]:
# file is saved in current directory 
# to view all the files in the directory use this command
%ls

 Volume in drive C is Windows
 Volume Serial Number is F885-EF5C

 Directory of C:\Users\bobby\Desktop\UB_PYTHON_COURSE\LECTURE_NOTES

07/08/2019  11:07 AM    <DIR>          .
07/08/2019  11:07 AM    <DIR>          ..
07/08/2019  08:46 AM    <DIR>          .ipynb_checkpoints
07/08/2019  11:07 AM             2,510 datafile.csv
07/08/2019  09:12 AM         1,461,248 Education_data.xls
07/08/2019  09:12 AM           139,202 Importing_Data.ipynb
07/08/2019  08:20 AM           138,489 Importing_Data_Python_Cheat_Sheet.pdf
06/07/2019  10:50 AM            35,744 INTRO_NumPy.ipynb
07/01/2019  10:58 AM            12,737 INTRO_NumPy1.ipynb
07/02/2019  12:00 PM            20,817 INTRO_NumPy2.ipynb
07/08/2019  11:07 AM            17,838 INTRO_NumPy3.ipynb
06/11/2019  12:08 PM            23,453 INTRO_PYTHON.ipynb
06/17/2019  03:27 PM           254,763 INTRO_PYTHON1_file_control&basic_computing.html
06/05/2019  11:38 AM             3,498 INTRO_PYTHON1_file_control&basic_computing.ipynb
06/17/2019  0

In [33]:
# to read in files that are saved in the directory
data = np.loadtxt("datafile.csv")

In [34]:
attendance = data[:,0:1]
grade_lvl = data[:,1:2]

In [35]:
attendance

array([[4.],
       [5.],
       [6.],
       [8.],
       [0.],
       [7.],
       [1.],
       [2.],
       [9.],
       [1.]])